# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NaradaBotDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NaradaBotDemo
  pod 'ApiAI', :git => 'https://github.com/Visual-Engineering/apiai-ios-client', :branch => 'fulfillmentJSON'
  pod 'JSQMessagesViewController'
  pod 'SDWebImage'

  target 'NaradaBotDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NaradaBotDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
